name: Blue Green Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Deploy via SSH
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USER }}
        key: ${{ secrets.VPS_SSH_KEY }}
        script: |
          cd /var/www/project/rivan_practice_web
        
          git pull origin main
        
          ACTIVE=$(cat .active_color)
        
          if [ "$ACTIVE" = "blue" ]; then
            NEW="green"
            OLD="blue"
          else
            NEW="blue"
            OLD="green"
          fi
        
          echo "Deploying to $NEW environment..."
        
          docker compose -f docker-compose.prod.yml up -d --build backend_$NEW frontend_$NEW
        
          echo "Waiting for backend to initialize..."
          sleep 8
        
          echo "Performing health check..."
        
          for i in {1..10}; do
            STATUS=$(docker exec prod_nginx curl -s -o /dev/null -w "%{http_code}" -H "Host: rivanacad.com" http://backend_$NEW:8000/health/)

            
            if [ "$STATUS" = "200" ]; then
              echo "Health check passed."
              break
            fi
        
            echo "Health check failed. Retrying..."
            sleep 3
          done
        
          if [ "$STATUS" != "200" ]; then
            echo "Deployment failed. Rolling back."
            docker stop backend_$NEW frontend_$NEW
            exit 1
          fi
        
          echo "Switching nginx upstream..."
        
          echo "upstream backend_upstream {
              server backend_$NEW:8000;
          }
        
          upstream frontend_upstream {
              server frontend_$NEW:5173;
          }" > nginx/upstream.conf
        
          docker exec prod_nginx nginx -s reload
        
          echo "$NEW" > .active_color
        
          echo "Stopping old environment..."
        
          docker stop backend_$OLD frontend_$OLD
        
          echo "Deployment complete."
